// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ogquzopoahnsqstzmvjw

class SupabaseConfig {
  static const String supabaseUrl = 'https://ogquzopoahnsqstzmvjw.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ncXV6b3BvYWhuc3FzdHptdmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNzIwMjIsImV4cCI6MjA3Nzk0ODAyMn0.dq5QrQKSwYB2bBtYGeq_LbN7eDFUL1C2Mty0FLHirL8';
}
